# Generated by Django 2.1.7 on 2019-04-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='file_path',
        ),
        migrations.AddField(
            model_name='model',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backend_service.DataSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.TextField(choices=[('CNN', 'cnn'), ('GRID', 'grid')], default='cnn', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='modified',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='uploaded',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='modified',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='uploaded',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
