# Generated by Django 2.1.7 on 2019-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0002_auto_20190402_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='checkpoint_path',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='model_path',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
