# Generated by Django 2.1.7 on 2019-04-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0004_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='type',
            field=models.TextField(choices=[('CNN', 'cnn'), ('GCNN', 'gcnn')], default='cnn', max_length=10),
        ),
    ]
